### ISSUE TITLE
ReferenceError: SimpleModule is not defined

### ISSUE THREAD

**Issue by wikimo** [ghostboyzone/angular-simditor#1]
错误信息：
ReferenceError: SimpleModule is not defined

root['Simditor'] = factory(jQuery,SimpleModule,simple.hotkeys,simple.uploader);

通过bower 安装，对应的版本是：Simditor v2.1.15，执行18行的时候似乎有问题，

需要如何解，谢谢，对 angular还不是很熟悉，请指点

**Comment by ghostboyzone** [comment]
在项目的bower.json中加入overrides

```
"overrides": {
    "simditor-html": {
      "main": [
        "lib/simditor-html.js",
        "styles/simditor-html.css"
      ]
    }
  }
```

**Comment by wikimo** [comment]
已经解决了，是我自己的问题，情况是可能顶部有导航，被遮挡了，      this.wrapper.css('top', this.opts.toolbarFloatOffset + 50);，后来发现了可配置参数。

# 

OK。谢谢，解决了，参考了https://github.com/ghostboyzone/angular-simditor/blob/master/tests/index.html ，有些库漏加载了。另外，toolbarFloat 属性似乎没有效果
